openapi: 3.0.3
info:
  title: 考核试题 API 文档
  description: |
    ## 项目介绍
    这是一个用于用户注册、登录及名片操作的API文档。
    ## 功能介绍
    (1)该名片小程序帮助用户展示个人信息、部门、联系方式等信息，每个用户可以拥有多张个人名片
    (2)用户注册：用手机号或者用户名注册
    (3)用户可以保存其他用户的名片，随时查询
    (4)用户可以把自己的名片二维码给他人扫描，从而展示自己的名片

    ##api模块
    - 用户注册与登录
    - 名片的创建、读取、更新与删除


  version: 1.0.0
  contact:
    name: 开发团队
    email: dev@example.com
servers:
  - url: http://localhost:3000/v1
    description: 本地开发环境

paths:
  /api/health:
    get:
      summary: 服务健康检查
      description: 用于检测服务是否正常运行
      responses:
        '200':
          description: 服务正常
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
components: {}